-- Phase 11B.2 — user-defined proposal numbers with permanent history
-- A used proposal number stays reserved for that user even after the proposal is deleted.

alter table public.proposals
  add column if not exists proposal_number text;

update public.proposals
set proposal_number =
  'ANG-' ||
  to_char(coalesce(created_at, now()), 'YYYY') ||
  '-' ||
  upper(substr(regexp_replace(public_token::text, '[^a-zA-Z0-9]', '', 'g'), 1, 6))
where proposal_number is null
   or btrim(proposal_number) = '';

alter table public.proposals
  alter column proposal_number set not null;

alter table public.proposals
  drop constraint if exists proposals_proposal_number_length_check;

alter table public.proposals
  add constraint proposals_proposal_number_length_check
  check (char_length(btrim(proposal_number)) between 1 and 64);

create table if not exists public.proposal_number_registry (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  proposal_id text not null,
  proposal_number text not null,
  normalized_number text not null,
  reserved_at timestamptz not null default now()
);

create unique index if not exists proposal_number_registry_user_number_uidx
  on public.proposal_number_registry (user_id, normalized_number);

create index if not exists proposal_number_registry_user_idx
  on public.proposal_number_registry (user_id, reserved_at desc);

alter table public.proposal_number_registry enable row level security;

drop policy if exists "Users can read own proposal number history"
  on public.proposal_number_registry;

create policy "Users can read own proposal number history"
  on public.proposal_number_registry
  for select
  using (auth.uid() = user_id);

create or replace function public.normalize_proposal_number(value text)
returns text
language sql
immutable
as $$
  select lower(regexp_replace(btrim(coalesce(value, '')), '\s+', ' ', 'g'));
$$;

insert into public.proposal_number_registry (
  user_id,
  proposal_id,
  proposal_number,
  normalized_number,
  reserved_at
)
select
  p.user_id,
  p.id::text,
  p.proposal_number,
  public.normalize_proposal_number(p.proposal_number),
  coalesce(p.created_at, now())
from public.proposals p
where btrim(p.proposal_number) <> ''
on conflict (user_id, normalized_number) do nothing;

create or replace function public.reserve_proposal_number_forever()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized text;
  reserved_by text;
begin
  new.proposal_number := btrim(new.proposal_number);

  if new.proposal_number is null
     or char_length(new.proposal_number) < 1
     or char_length(new.proposal_number) > 64 then
    raise exception 'Die Angebotsnummer muss zwischen 1 und 64 Zeichen lang sein.'
      using errcode = '23514';
  end if;

  normalized := public.normalize_proposal_number(new.proposal_number);

  select r.proposal_id
    into reserved_by
  from public.proposal_number_registry r
  where r.user_id = new.user_id
    and r.normalized_number = normalized
  limit 1;

  if found then
    if reserved_by is distinct from new.id::text then
      raise exception 'Die Angebotsnummer "%" wurde bereits verwendet und bleibt dauerhaft reserviert.', new.proposal_number
        using errcode = '23505';
    end if;
    return new;
  end if;

  begin
    insert into public.proposal_number_registry (
      user_id,
      proposal_id,
      proposal_number,
      normalized_number
    ) values (
      new.user_id,
      new.id::text,
      new.proposal_number,
      normalized
    );
  exception when unique_violation then
    raise exception 'Die Angebotsnummer "%" wurde bereits verwendet und bleibt dauerhaft reserviert.', new.proposal_number
      using errcode = '23505';
  end;

  return new;
end;
$$;

drop trigger if exists proposals_reserve_number_forever
  on public.proposals;

create trigger proposals_reserve_number_forever
before insert or update of proposal_number
on public.proposals
for each row
execute function public.reserve_proposal_number_forever();
