-- Phase 11B.3 — proposal number semantics
--
-- Rules:
-- 1) A proposal number may only be used by one active proposal at a time.
-- 2) DECLINED proposals release their number so it may be reused.
-- 3) Deleted DRAFT/SENT/DECLINED proposals also release their number.
-- 4) Once a proposal is ACCEPTED, its number is permanently reserved for that user,
--    even if the accepted proposal is deleted later.
--
-- This migration is safe whether Phase 11B.2 SQL was never run or was partially run.

begin;

create or replace function public.normalize_proposal_number(value text)
returns text
language sql
immutable
as $$
  select lower(regexp_replace(btrim(coalesce(value, '')), '\s+', ' ', 'g'));
$$;

alter table public.proposals
  add column if not exists proposal_number text;

-- Existing proposals need a stable number so the new NOT NULL field does not break
-- old records. Users can replace this generated value in the Proposal Builder.
update public.proposals
set proposal_number =
  'ANG-' ||
  to_char(coalesce(created_at, now()), 'YYYY') ||
  '-' ||
  upper(substr(regexp_replace(public_token::text, '[^a-zA-Z0-9]', '', 'g'), 1, 6))
where proposal_number is null
   or btrim(proposal_number) = '';

alter table public.proposals
  alter column proposal_number set not null;

alter table public.proposals
  drop constraint if exists proposals_proposal_number_length_check;

alter table public.proposals
  add constraint proposals_proposal_number_length_check
  check (char_length(btrim(proposal_number)) between 1 and 64);

create table if not exists public.proposal_number_registry (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  proposal_id text not null,
  proposal_number text not null,
  normalized_number text not null,
  reserved_at timestamptz not null default now()
);

alter table public.proposal_number_registry
  add column if not exists accepted_at timestamptz;

-- Phase 11B.2 temporarily reserved every saved number. Correct that behavior:
-- existing non-accepted proposals must NOT live in the permanent registry.
delete from public.proposal_number_registry r
using public.proposals p
where p.id::text = r.proposal_id
  and p.status <> 'ACCEPTED';

-- Mark known accepted reservations and backfill accepted proposals.
update public.proposal_number_registry r
set accepted_at = coalesce(r.accepted_at, p.accepted_at, p.responded_at, r.reserved_at)
from public.proposals p
where p.id::text = r.proposal_id
  and p.status = 'ACCEPTED';

create unique index if not exists proposal_number_registry_user_number_uidx
  on public.proposal_number_registry (user_id, normalized_number);

create index if not exists proposal_number_registry_user_idx
  on public.proposal_number_registry (user_id, reserved_at desc);

insert into public.proposal_number_registry (
  user_id,
  proposal_id,
  proposal_number,
  normalized_number,
  reserved_at,
  accepted_at
)
select
  p.user_id,
  p.id::text,
  p.proposal_number,
  public.normalize_proposal_number(p.proposal_number),
  coalesce(p.accepted_at, p.responded_at, p.created_at, now()),
  coalesce(p.accepted_at, p.responded_at, p.created_at, now())
from public.proposals p
where p.status = 'ACCEPTED'
  and btrim(p.proposal_number) <> ''
on conflict (user_id, normalized_number) do nothing;

alter table public.proposal_number_registry enable row level security;

drop policy if exists "Users can read own proposal number history"
  on public.proposal_number_registry;

create policy "Users can read own proposal number history"
  on public.proposal_number_registry
  for select
  using (auth.uid() = user_id);

-- Remove Phase 11B.2's old "reserve on every save" trigger if it exists.
drop trigger if exists proposals_reserve_number_forever
  on public.proposals;

drop function if exists public.reserve_proposal_number_forever();

-- A permanently reserved number may never be assigned to a different proposal.
create or replace function public.guard_permanently_reserved_proposal_number()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized text;
  reserved_by text;
begin
  new.proposal_number := btrim(new.proposal_number);

  if new.proposal_number is null
     or char_length(new.proposal_number) < 1
     or char_length(new.proposal_number) > 64 then
    raise exception 'Die Angebotsnummer muss zwischen 1 und 64 Zeichen lang sein.'
      using errcode = '23514';
  end if;

  normalized := public.normalize_proposal_number(new.proposal_number);

  select r.proposal_id
    into reserved_by
  from public.proposal_number_registry r
  where r.user_id = new.user_id
    and r.normalized_number = normalized
  limit 1;

  if found and reserved_by is distinct from new.id::text then
    raise exception 'Die Angebotsnummer "%" wurde bereits von einem angenommenen Angebot verwendet und bleibt dauerhaft reserviert.', new.proposal_number
      using errcode = '23505';
  end if;

  return new;
end;
$$;

drop trigger if exists proposals_guard_permanent_number
  on public.proposals;

create trigger proposals_guard_permanent_number
before insert or update of proposal_number, user_id
on public.proposals
for each row
execute function public.guard_permanently_reserved_proposal_number();

-- While a proposal still exists and has not been declined, its number is occupied.
-- DECLINED rows are intentionally excluded so the number becomes reusable.
drop index if exists proposals_user_active_proposal_number_uidx;

create unique index proposals_user_active_proposal_number_uidx
  on public.proposals (
    user_id,
    public.normalize_proposal_number(proposal_number)
  )
  where status <> 'DECLINED';

-- Only acceptance makes a number permanent.
create or replace function public.reserve_proposal_number_on_acceptance()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized text;
  reserved_by text;
  accepted_time timestamptz;
begin
  if new.status <> 'ACCEPTED' then
    return new;
  end if;

  if tg_op = 'UPDATE'
     and old.status = 'ACCEPTED'
     and old.proposal_number is not distinct from new.proposal_number then
    return new;
  end if;

  normalized := public.normalize_proposal_number(new.proposal_number);
  accepted_time := coalesce(new.accepted_at, new.responded_at, now());

  insert into public.proposal_number_registry (
    user_id,
    proposal_id,
    proposal_number,
    normalized_number,
    reserved_at,
    accepted_at
  ) values (
    new.user_id,
    new.id::text,
    new.proposal_number,
    normalized,
    accepted_time,
    accepted_time
  )
  on conflict (user_id, normalized_number) do nothing;

  select r.proposal_id
    into reserved_by
  from public.proposal_number_registry r
  where r.user_id = new.user_id
    and r.normalized_number = normalized
  limit 1;

  if reserved_by is distinct from new.id::text then
    raise exception 'Die Angebotsnummer "%" wurde bereits von einem anderen angenommenen Angebot verwendet.', new.proposal_number
      using errcode = '23505';
  end if;

  return new;
end;
$$;

drop trigger if exists proposals_reserve_number_on_acceptance
  on public.proposals;

create trigger proposals_reserve_number_on_acceptance
after insert or update of status, proposal_number
on public.proposals
for each row
execute function public.reserve_proposal_number_on_acceptance();

commit;
