-- Phase 11B.4 — per-user Leadbase AI usage ledger + optional monthly token cap
-- Safe to run multiple times.

begin;

create table if not exists public.ai_usage_accounts (
  user_id uuid primary key references auth.users(id) on delete cascade,
  plan_id text not null default 'development',
  monthly_token_limit bigint,
  purchased_token_balance bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ai_usage_accounts_monthly_limit_check
    check (monthly_token_limit is null or monthly_token_limit >= 0),
  constraint ai_usage_accounts_purchased_balance_check
    check (purchased_token_balance >= 0)
);

create table if not exists public.ai_usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  feature text not null,
  model text,
  input_tokens bigint not null default 0,
  output_tokens bigint not null default 0,
  total_tokens bigint not null default 0,
  request_key text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint ai_usage_events_tokens_check
    check (input_tokens >= 0 and output_tokens >= 0 and total_tokens >= 0)
);

create unique index if not exists ai_usage_events_request_key_uidx
  on public.ai_usage_events (user_id, request_key)
  where request_key is not null;

create index if not exists ai_usage_events_user_created_idx
  on public.ai_usage_events (user_id, created_at desc);

create index if not exists ai_usage_events_user_feature_created_idx
  on public.ai_usage_events (user_id, feature, created_at desc);

alter table public.ai_usage_accounts enable row level security;
alter table public.ai_usage_events enable row level security;

drop policy if exists "Users can read own AI usage account" on public.ai_usage_accounts;
create policy "Users can read own AI usage account"
  on public.ai_usage_accounts
  for select
  using (auth.uid() = user_id);

drop policy if exists "Users can read own AI usage events" on public.ai_usage_events;
create policy "Users can read own AI usage events"
  on public.ai_usage_events
  for select
  using (auth.uid() = user_id);

-- Ensure every existing user has an unlimited development account unless an
-- explicit limit was already configured.
insert into public.ai_usage_accounts (user_id, plan_id, monthly_token_limit)
select id, 'development', null
from auth.users
on conflict (user_id) do nothing;

-- Keep realtime enabled so the sidebar/profile can update immediately after
-- a metered AI request is recorded.
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
     and not exists (
       select 1
       from pg_publication_tables
       where pubname = 'supabase_realtime'
         and schemaname = 'public'
         and tablename = 'ai_usage_events'
     ) then
    alter publication supabase_realtime add table public.ai_usage_events;
  end if;
end $$;

-- Backfill the current month from token fields Leadbase already stored before
-- this ledger existed. request_key makes the migration idempotent.
insert into public.ai_usage_events (
  user_id, feature, model, input_tokens, output_tokens, total_tokens,
  request_key, metadata, created_at
)
select
  d.user_id,
  'outreach_generation',
  d.model,
  greatest(coalesce(d.input_tokens, 0), 0),
  greatest(coalesce(d.output_tokens, 0), 0),
  greatest(coalesce(d.total_tokens, 0), 0),
  'backfill:outreach:' || d.id::text,
  jsonb_build_object('draftId', d.id, 'backfilled', true),
  coalesce(d.created_at, now())
from public.outreach_drafts d
where coalesce(d.total_tokens, 0) > 0
  and coalesce(d.created_at, now()) >= date_trunc('month', now())
on conflict (user_id, request_key) where request_key is not null do nothing;

insert into public.ai_usage_events (
  user_id, feature, model, input_tokens, output_tokens, total_tokens,
  request_key, metadata, created_at
)
select
  l.user_id,
  'lead_analysis',
  l.visual_model,
  greatest(coalesce(l.visual_input_tokens, 0), 0),
  greatest(coalesce(l.visual_output_tokens, 0), 0),
  greatest(coalesce(l.visual_total_tokens, 0), 0),
  'backfill:lead-analysis:' || l.id::text || ':' || coalesce(l.visual_analyzed_at::text, 'unknown'),
  jsonb_build_object('leadId', l.id, 'backfilled', true),
  coalesce(l.visual_analyzed_at, l.analyzed_at, l.updated_at, now())
from public.leads l
where coalesce(l.visual_total_tokens, 0) > 0
  and coalesce(l.visual_analyzed_at, l.analyzed_at, l.updated_at, now()) >= date_trunc('month', now())
on conflict (user_id, request_key) where request_key is not null do nothing;

commit;
