-- Phase 13 — Billing, Credits & Cost Protection
-- Run once in Supabase SQL editor before enabling Stripe checkout routes.
-- Idempotent: safe to re-run.

begin;

alter table public.ai_usage_accounts
  add column if not exists plan_tier_index integer not null default 0,
  add column if not exists billing_interval text not null default 'monthly',
  add column if not exists subscription_status text not null default 'free',
  add column if not exists monthly_credit_limit bigint not null default 0,
  add column if not exists plan_credit_balance bigint not null default 0,
  add column if not exists purchased_credit_balance bigint not null default 0,
  add column if not exists credit_debt_balance bigint not null default 0,
  add column if not exists credit_period_started_at timestamptz,
  add column if not exists credit_period_resets_at timestamptz,
  add column if not exists stripe_customer_id text,
  add column if not exists stripe_subscription_id text,
  add column if not exists subscription_current_period_end timestamptz,
  add column if not exists cancel_at_period_end boolean not null default false,
  add column if not exists free_signup_credits_granted boolean not null default false;

alter table public.ai_usage_events
  add column if not exists cached_input_tokens bigint not null default 0,
  add column if not exists provider_cost_usd numeric(18,8) not null default 0,
  add column if not exists credits_charged bigint not null default 0,
  add column if not exists pricing_version text;

-- Remove the old unlimited-development semantics. The old token columns remain
-- for rollback compatibility but Phase 13 no longer uses them for enforcement.
update public.ai_usage_accounts
set plan_id = 'free',
    monthly_token_limit = 0,
    purchased_token_balance = 0,
    subscription_status = 'free',
    updated_at = now()
where plan_id = 'development';

create table if not exists public.ai_credit_reservations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  request_key text not null,
  feature text not null,
  model text,
  reserved_credits bigint not null,
  plan_credits_reserved bigint not null default 0,
  purchased_credits_reserved bigint not null default 0,
  actual_credits bigint,
  provider_cost_usd numeric(18,8),
  status text not null default 'reserved',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '45 minutes'),
  settled_at timestamptz,
  constraint ai_credit_reservations_reserved_check check (reserved_credits >= 0),
  constraint ai_credit_reservations_plan_check check (plan_credits_reserved >= 0),
  constraint ai_credit_reservations_purchased_check check (purchased_credits_reserved >= 0),
  constraint ai_credit_reservations_status_check check (status in ('reserved','settled','released','expired')),
  unique (user_id, request_key)
);

create table if not exists public.ai_credit_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  amount bigint not null,
  kind text not null,
  source text,
  request_key text,
  provider_cost_usd numeric(18,8) not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create unique index if not exists ai_credit_transactions_user_request_uidx
  on public.ai_credit_transactions (user_id, request_key)
  where request_key is not null;

create index if not exists ai_credit_transactions_user_created_idx
  on public.ai_credit_transactions (user_id, created_at desc);

create index if not exists ai_credit_reservations_user_status_idx
  on public.ai_credit_reservations (user_id, status, expires_at);

create table if not exists public.stripe_webhook_events (
  event_id text primary key,
  event_type text not null,
  status text not null default 'processing',
  error text,
  processed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint stripe_webhook_events_status_check check (status in ('processing','processed','failed'))
);

create unique index if not exists ai_usage_accounts_stripe_customer_uidx
  on public.ai_usage_accounts (stripe_customer_id)
  where stripe_customer_id is not null;

create unique index if not exists ai_usage_accounts_stripe_subscription_uidx
  on public.ai_usage_accounts (stripe_subscription_id)
  where stripe_subscription_id is not null;

alter table public.ai_credit_reservations enable row level security;
alter table public.ai_credit_transactions enable row level security;
alter table public.stripe_webhook_events enable row level security;

drop policy if exists "Users can read own credit reservations" on public.ai_credit_reservations;
create policy "Users can read own credit reservations"
  on public.ai_credit_reservations for select
  using (auth.uid() = user_id);

drop policy if exists "Users can read own credit transactions" on public.ai_credit_transactions;
create policy "Users can read own credit transactions"
  on public.ai_credit_transactions for select
  using (auth.uid() = user_id);

-- No client policy is intentionally created for stripe_webhook_events.

-- Existing users receive a small one-time free trial wallet. It does not reset.
insert into public.ai_usage_accounts (
  user_id, plan_id, subscription_status, monthly_credit_limit,
  plan_credit_balance, purchased_credit_balance, free_signup_credits_granted,
  monthly_token_limit, purchased_token_balance
)
select id, 'free', 'free', 0, 0, 50, true, 0, 0
from auth.users
on conflict (user_id) do nothing;

update public.ai_usage_accounts
set purchased_credit_balance = purchased_credit_balance + 50,
    free_signup_credits_granted = true,
    plan_id = case when plan_id = 'development' then 'free' else plan_id end,
    subscription_status = case when plan_id in ('free','development') then 'free' else subscription_status end,
    monthly_token_limit = 0,
    purchased_token_balance = 0,
    updated_at = now()
where free_signup_credits_granted = false;

-- Every future Supabase auth user gets the same limited free wallet.
create or replace function public.leadbase_create_credit_account_for_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.ai_usage_accounts (
    user_id, plan_id, subscription_status, monthly_credit_limit,
    plan_credit_balance, purchased_credit_balance, free_signup_credits_granted,
    monthly_token_limit, purchased_token_balance
  ) values (
    new.id, 'free', 'free', 0, 0, 50, true, 0, 0
  ) on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists leadbase_create_credit_account_after_signup on auth.users;
create trigger leadbase_create_credit_account_after_signup
after insert on auth.users
for each row execute function public.leadbase_create_credit_account_for_new_user();

-- Release stale reservations and refresh the monthly plan-wallet on demand.
create or replace function public.leadbase_refresh_credit_period(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  acc public.ai_usage_accounts%rowtype;
  r public.ai_credit_reservations%rowtype;
  next_reset timestamptz;
begin
  insert into public.ai_usage_accounts (
    user_id, plan_id, subscription_status, monthly_credit_limit,
    plan_credit_balance, purchased_credit_balance, free_signup_credits_granted,
    monthly_token_limit, purchased_token_balance
  ) values (p_user_id, 'free', 'free', 0, 0, 50, true, 0, 0)
  on conflict (user_id) do nothing;

  select * into acc
  from public.ai_usage_accounts
  where user_id = p_user_id
  for update;

  -- Return expired reservations before calculating available balance.
  for r in
    select * from public.ai_credit_reservations
    where user_id = p_user_id
      and status = 'reserved'
      and expires_at <= now()
    for update
  loop
    update public.ai_usage_accounts
    set plan_credit_balance = plan_credit_balance + r.plan_credits_reserved,
        purchased_credit_balance = purchased_credit_balance + r.purchased_credits_reserved,
        updated_at = now()
    where user_id = p_user_id;

    update public.ai_credit_reservations
    set status = 'expired', settled_at = now()
    where id = r.id;
  end loop;

  select * into acc
  from public.ai_usage_accounts
  where user_id = p_user_id
  for update;

  -- A paid plan that is no longer active cannot keep spending plan credits.
  if acc.plan_id <> 'free' and acc.subscription_status not in ('active','trialing') then
    update public.ai_usage_accounts
    set plan_credit_balance = 0,
        updated_at = now()
    where user_id = p_user_id;
    return;
  end if;

  if acc.plan_id <> 'free'
     and acc.monthly_credit_limit > 0
     and acc.credit_period_resets_at is not null
     and acc.credit_period_resets_at <= now() then

    -- Reservations from the old month are released before the wallet reset.
    for r in
      select * from public.ai_credit_reservations
      where user_id = p_user_id and status = 'reserved'
      for update
    loop
      update public.ai_usage_accounts
      set plan_credit_balance = plan_credit_balance + r.plan_credits_reserved,
          purchased_credit_balance = purchased_credit_balance + r.purchased_credits_reserved,
          updated_at = now()
      where user_id = p_user_id;
      update public.ai_credit_reservations
      set status = 'expired', settled_at = now()
      where id = r.id;
    end loop;

    next_reset := acc.credit_period_resets_at;
    while next_reset <= now() loop
      next_reset := next_reset + interval '1 month';
    end loop;

    update public.ai_usage_accounts
    set plan_credit_balance = monthly_credit_limit,
        credit_period_started_at = next_reset - interval '1 month',
        credit_period_resets_at = next_reset,
        updated_at = now()
    where user_id = p_user_id;
  end if;
end;
$$;

create or replace function public.leadbase_reserve_credits(
  p_user_id uuid,
  p_request_key text,
  p_credits bigint,
  p_feature text,
  p_model text,
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  acc public.ai_usage_accounts%rowtype;
  existing public.ai_credit_reservations%rowtype;
  use_plan bigint;
  use_purchased bigint;
begin
  if p_credits <= 0 then raise exception 'invalid credit reservation'; end if;
  perform public.leadbase_refresh_credit_period(p_user_id);

  select * into existing from public.ai_credit_reservations
  where user_id = p_user_id and request_key = p_request_key;
  if found then
    return jsonb_build_object('reserved_credits', existing.reserved_credits, 'status', existing.status);
  end if;

  select * into acc from public.ai_usage_accounts where user_id = p_user_id for update;
  if acc.credit_debt_balance > 0 then raise exception 'credit debt outstanding'; end if;
  if acc.plan_credit_balance + acc.purchased_credit_balance < p_credits then
    raise exception 'insufficient credits';
  end if;

  use_plan := least(acc.plan_credit_balance, p_credits);
  use_purchased := p_credits - use_plan;

  update public.ai_usage_accounts
  set plan_credit_balance = plan_credit_balance - use_plan,
      purchased_credit_balance = purchased_credit_balance - use_purchased,
      updated_at = now()
  where user_id = p_user_id;

  insert into public.ai_credit_reservations (
    user_id, request_key, feature, model, reserved_credits,
    plan_credits_reserved, purchased_credits_reserved, metadata
  ) values (
    p_user_id, p_request_key, coalesce(p_feature,'other'), p_model, p_credits,
    use_plan, use_purchased, coalesce(p_metadata,'{}'::jsonb)
  );

  return jsonb_build_object(
    'reserved_credits', p_credits,
    'plan_credits_reserved', use_plan,
    'purchased_credits_reserved', use_purchased,
    'status', 'reserved'
  );
end;
$$;

create or replace function public.leadbase_release_credit_reservation(
  p_user_id uuid,
  p_request_key text,
  p_reason text default 'released'
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  r public.ai_credit_reservations%rowtype;
begin
  select * into r from public.ai_credit_reservations
  where user_id = p_user_id and request_key = p_request_key
  for update;

  if not found or r.status <> 'reserved' then return; end if;

  update public.ai_usage_accounts
  set plan_credit_balance = plan_credit_balance + r.plan_credits_reserved,
      purchased_credit_balance = purchased_credit_balance + r.purchased_credits_reserved,
      updated_at = now()
  where user_id = p_user_id;

  update public.ai_credit_reservations
  set status = 'released',
      settled_at = now(),
      metadata = metadata || jsonb_build_object('releaseReason', p_reason)
  where id = r.id;
end;
$$;

create or replace function public.leadbase_settle_credit_reservation(
  p_user_id uuid,
  p_request_key text,
  p_actual_credits bigint,
  p_provider_cost_usd numeric,
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  r public.ai_credit_reservations%rowtype;
  acc public.ai_usage_accounts%rowtype;
  consume_plan bigint := 0;
  consume_purchased bigint := 0;
  refund_plan bigint := 0;
  refund_purchased bigint := 0;
  extra bigint := 0;
  extra_plan bigint := 0;
  extra_purchased bigint := 0;
  shortfall bigint := 0;
  actual bigint := greatest(coalesce(p_actual_credits,0),0);
begin
  select * into r from public.ai_credit_reservations
  where user_id = p_user_id and request_key = p_request_key
  for update;

  if found and r.status = 'settled' then
    return jsonb_build_object('charged_credits', coalesce(r.actual_credits, actual), 'status', 'settled');
  end if;

  if not found or r.status <> 'reserved' then
    -- Reservation expired/released after the provider started. Charge directly.
    return public.leadbase_charge_credits(
      p_user_id, 'late:' || p_request_key, actual,
      coalesce(r.feature,'other'), r.model, p_provider_cost_usd,
      coalesce(p_metadata,'{}'::jsonb) || jsonb_build_object('lateSettlement', true)
    );
  end if;

  consume_plan := least(actual, r.plan_credits_reserved);
  consume_purchased := least(greatest(actual - consume_plan, 0), r.purchased_credits_reserved);
  refund_plan := r.plan_credits_reserved - consume_plan;
  refund_purchased := r.purchased_credits_reserved - consume_purchased;
  extra := greatest(actual - r.reserved_credits, 0);

  update public.ai_usage_accounts
  set plan_credit_balance = plan_credit_balance + refund_plan,
      purchased_credit_balance = purchased_credit_balance + refund_purchased,
      updated_at = now()
  where user_id = p_user_id;

  if extra > 0 then
    select * into acc from public.ai_usage_accounts where user_id = p_user_id for update;
    extra_plan := least(acc.plan_credit_balance, extra);
    extra_purchased := least(acc.purchased_credit_balance, extra - extra_plan);
    shortfall := extra - extra_plan - extra_purchased;

    update public.ai_usage_accounts
    set plan_credit_balance = plan_credit_balance - extra_plan,
        purchased_credit_balance = purchased_credit_balance - extra_purchased,
        credit_debt_balance = credit_debt_balance + shortfall,
        updated_at = now()
    where user_id = p_user_id;
  end if;

  update public.ai_credit_reservations
  set status = 'settled',
      actual_credits = actual,
      provider_cost_usd = greatest(coalesce(p_provider_cost_usd,0),0),
      metadata = metadata || coalesce(p_metadata,'{}'::jsonb),
      settled_at = now()
  where id = r.id;

  insert into public.ai_credit_transactions (
    user_id, amount, kind, source, request_key, provider_cost_usd, metadata
  ) values (
    p_user_id, -actual, 'usage', r.feature, 'settle:' || p_request_key,
    greatest(coalesce(p_provider_cost_usd,0),0),
    coalesce(p_metadata,'{}'::jsonb) || jsonb_build_object('model', r.model, 'debtCreated', shortfall)
  ) on conflict (user_id, request_key) where request_key is not null do nothing;

  return jsonb_build_object('charged_credits', actual, 'debt_created', shortfall, 'status', 'settled');
end;
$$;

create or replace function public.leadbase_charge_credits(
  p_user_id uuid,
  p_request_key text,
  p_credits bigint,
  p_feature text,
  p_model text,
  p_provider_cost_usd numeric,
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  acc public.ai_usage_accounts%rowtype;
  existing_amount bigint;
  use_plan bigint := 0;
  use_purchased bigint := 0;
  shortfall bigint := 0;
  credits bigint := greatest(coalesce(p_credits,0),0);
begin
  select abs(amount) into existing_amount from public.ai_credit_transactions
  where user_id = p_user_id and request_key = p_request_key;
  if found then return jsonb_build_object('charged_credits', existing_amount, 'status', 'already_charged'); end if;

  perform public.leadbase_refresh_credit_period(p_user_id);
  select * into acc from public.ai_usage_accounts where user_id = p_user_id for update;

  use_plan := least(acc.plan_credit_balance, credits);
  use_purchased := least(acc.purchased_credit_balance, credits - use_plan);
  shortfall := credits - use_plan - use_purchased;

  update public.ai_usage_accounts
  set plan_credit_balance = plan_credit_balance - use_plan,
      purchased_credit_balance = purchased_credit_balance - use_purchased,
      credit_debt_balance = credit_debt_balance + shortfall,
      updated_at = now()
  where user_id = p_user_id;

  insert into public.ai_credit_transactions (
    user_id, amount, kind, source, request_key, provider_cost_usd, metadata
  ) values (
    p_user_id, -credits, 'usage', coalesce(p_feature,'other'), p_request_key,
    greatest(coalesce(p_provider_cost_usd,0),0),
    coalesce(p_metadata,'{}'::jsonb) || jsonb_build_object('model', p_model, 'debtCreated', shortfall)
  );

  return jsonb_build_object('charged_credits', credits, 'debt_created', shortfall, 'status', 'charged');
end;
$$;

create or replace function public.leadbase_grant_credits(
  p_user_id uuid,
  p_credits bigint,
  p_idempotency_key text,
  p_source text,
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  acc public.ai_usage_accounts%rowtype;
  existing_amount bigint;
  credits bigint := greatest(coalesce(p_credits,0),0);
  debt_paid bigint := 0;
  wallet_added bigint := 0;
begin
  if credits <= 0 then raise exception 'invalid credit grant'; end if;

  select amount into existing_amount from public.ai_credit_transactions
  where user_id = p_user_id and request_key = p_idempotency_key;
  if found then return jsonb_build_object('granted_credits', existing_amount, 'status', 'already_granted'); end if;

  perform public.leadbase_refresh_credit_period(p_user_id);
  select * into acc from public.ai_usage_accounts where user_id = p_user_id for update;

  debt_paid := least(acc.credit_debt_balance, credits);
  wallet_added := credits - debt_paid;

  update public.ai_usage_accounts
  set credit_debt_balance = credit_debt_balance - debt_paid,
      purchased_credit_balance = purchased_credit_balance + wallet_added,
      updated_at = now()
  where user_id = p_user_id;

  insert into public.ai_credit_transactions (
    user_id, amount, kind, source, request_key, metadata
  ) values (
    p_user_id, credits, 'grant', p_source, p_idempotency_key,
    coalesce(p_metadata,'{}'::jsonb) || jsonb_build_object('debtPaid', debt_paid, 'walletAdded', wallet_added)
  );

  return jsonb_build_object('granted_credits', credits, 'debt_paid', debt_paid, 'wallet_added', wallet_added, 'status', 'granted');
end;
$$;


create index if not exists ai_usage_events_created_cost_idx
  on public.ai_usage_events (created_at desc);

create or replace function public.leadbase_cost_guard_snapshot(p_user_id uuid)
returns jsonb
language sql
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'user_day_usd', coalesce((select sum(provider_cost_usd) from public.ai_usage_events where user_id = p_user_id and created_at >= date_trunc('day', now() at time zone 'utc') at time zone 'utc'), 0),
    'global_day_usd', coalesce((select sum(provider_cost_usd) from public.ai_usage_events where created_at >= date_trunc('day', now() at time zone 'utc') at time zone 'utc'), 0),
    'global_month_usd', coalesce((select sum(provider_cost_usd) from public.ai_usage_events where created_at >= date_trunc('month', now() at time zone 'utc') at time zone 'utc'), 0)
  );
$$;

-- Mutating billing RPCs are server-only. RLS is not enough for SECURITY DEFINER functions.
revoke all on function public.leadbase_cost_guard_snapshot(uuid) from public, anon, authenticated;
revoke all on function public.leadbase_refresh_credit_period(uuid) from public, anon, authenticated;
revoke all on function public.leadbase_reserve_credits(uuid,text,bigint,text,text,jsonb) from public, anon, authenticated;
revoke all on function public.leadbase_release_credit_reservation(uuid,text,text) from public, anon, authenticated;
revoke all on function public.leadbase_settle_credit_reservation(uuid,text,bigint,numeric,jsonb) from public, anon, authenticated;
revoke all on function public.leadbase_charge_credits(uuid,text,bigint,text,text,numeric,jsonb) from public, anon, authenticated;
revoke all on function public.leadbase_grant_credits(uuid,bigint,text,text,jsonb) from public, anon, authenticated;

grant execute on function public.leadbase_cost_guard_snapshot(uuid) to service_role;
grant execute on function public.leadbase_refresh_credit_period(uuid) to service_role;
grant execute on function public.leadbase_reserve_credits(uuid,text,bigint,text,text,jsonb) to service_role;
grant execute on function public.leadbase_release_credit_reservation(uuid,text,text) to service_role;
grant execute on function public.leadbase_settle_credit_reservation(uuid,text,bigint,numeric,jsonb) to service_role;
grant execute on function public.leadbase_charge_credits(uuid,text,bigint,text,text,numeric,jsonb) to service_role;
grant execute on function public.leadbase_grant_credits(uuid,bigint,text,text,jsonb) to service_role;

commit;
